version: '3.8'

services:
  node_app:
    build:
      context: ../
      dockerfile: ci-cd/Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      # Uncomment and update if using Postgres
      # - DATABASE_URL=postgres://postgres:postgres@postgres_db:5432/mydb
    depends_on:
      - postgres_db
    networks:
      - monitoring_net

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge

