pipeline {
    agent any

    environment {
        IMAGE_NAME = "madhan1205/boiler"
        IMAGE_TAG  = "${env.BUILD_NUMBER}"
        APP_DIR    = "boilerplate2"
        DOCKERFILE_PATH = "boilerplate2/ci-cd/Dockerfile"
        TERRAFORM_DIR = "boilerplate2/terraform"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/MADHAN-KUMAR-G/boilerplate-proj2-.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${APP_DIR}") {
                    sh 'yarn install --frozen-lockfile || yarn install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME}:latest ${APP_DIR}"
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', 
                                                  usernameVariable: 'DOCKER_USER', 
                                                  passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir("${TERRAFORM_DIR}") {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }

    post {
        always {
            sh 'docker ps -a'
        }
    }
}

